# Generated by Django 3.2.5 on 2021-08-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudOperations', '0002_auto_20210810_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='Game_Content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='Game_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
