# Generated by Django 3.2.5 on 2021-08-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudOperations', '0003_auto_20210810_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='Game_Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
