# Generated by Django 3.2.5 on 2021-08-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudOperations', '0008_auto_20210810_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='available',
            name='tags',
            field=models.ManyToManyField(to='crudOperations.Tag'),
        ),
    ]
